/** @type {import('tailwindcss').Config} */
import daisyui from "daisyui";

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  // Don't strip the custom utility classes the older pages use (page-card,
  // btn, etc.). The custom CSS in src/styles/global.css remains the source
  // of truth for those — Tailwind is layered on top for components that
  // opted into utility classes (login, scans, findings, AI assistant).
  important: false,
  safelist: [
    "min-h-screen",
    "bg-base-300",
    "bg-base-200",
    "bg-base-100",
    "bg-primary",
    "bg-primary/10",
    "bg-primary/80",
    "bg-warning/10",
    "bg-error/10",
    "bg-error",
    "text-primary",
    "text-primary-content",
    "text-error",
    "text-warning",
    "text-success",
    "text-info",
    "text-base-content",
    "text-base-content/20",
    "text-base-content/30",
    "text-base-content/40",
    "text-base-content/60",
    "border-base-300",
    "border-primary",
    "border-warning/20",
    "border-error/20",
    "border-error/30",
    "border-warning/30",
    "border-info/30",
    "ring-primary/30",
    "ring-base-content/40",
    "ring-offset-1",
    "ring-offset-base-100",
    "card",
    "card-body",
    "btn",
    "btn-primary",
    "btn-outline",
    "btn-ghost",
    "btn-sm",
    "btn-xs",
    "btn-square",
    "input",
    "input-bordered",
    "select",
    "select-bordered",
    "select-sm",
    "textarea",
    "textarea-bordered",
    "textarea-sm",
    "badge",
    "badge-sm",
    "badge-error",
    "badge-warning",
    "badge-info",
    "badge-success",
    "badge-ghost",
    "badge-outline",
    "alert",
    "alert-error",
    "progress",
    "progress-primary",
    "loading",
    "loading-spinner",
    "loading-sm",
    "loading-lg",
    "divider",
    "form-control",
    "label",
    "label-text",
    "join",
    "join-item",
    "link",
    "link-primary",
    "menu",
    "modal",
    "modal-box",
    "shadow",
    "shadow-sm",
    "shadow-lg",
    "shadow-xl",
    "shadow-2xl",
    "rounded",
    "rounded-md",
    "rounded-lg",
    "rounded-xl",
    "rounded-2xl",
    "rounded-full",
    "fixed",
    "relative",
    "absolute",
    "inset-0",
    "top-",
    "right-",
    "bottom-",
    "left-",
    "z-40",
    "z-50",
    "w-3",
    "w-4",
    "w-5",
    "w-6",
    "w-8",
    "w-10",
    "w-12",
    "w-14",
    "w-16",
    "w-20",
    "w-80",
    "w-96",
    "h-3",
    "h-4",
    "h-5",
    "h-6",
    "h-8",
    "h-10",
    "h-12",
    "h-14",
    "h-16",
    "h-20",
    "max-w-md",
    "max-w-\\[85\\%\\]",
    "max-h-\\[600px\\]",
    "max-h-\\[320px\\]",
    "max-h-48",
    "min-h-0",
    "min-h-screen",
    "min-h-\\[36px\\]",
    "max-h-\\[80px\\]",
    "p-",
    "px-",
    "py-",
    "m-",
    "mx-",
    "my-",
    "mt-",
    "mb-",
    "ml-",
    "mr-",
    "gap-",
    "space-y-",
    "space-x-",
    "flex",
    "inline-flex",
    "grid",
    "items-center",
    "items-start",
    "items-end",
    "justify-center",
    "justify-between",
    "justify-end",
    "justify-start",
    "flex-col",
    "flex-row",
    "flex-wrap",
    "flex-1",
    "shrink-0",
    "min-w-0",
    "truncate",
    "text-center",
    "text-xs",
    "text-sm",
    "text-lg",
    "text-xl",
    "text-2xl",
    "text-3xl",
    "text-\\[10px\\]",
    "font-bold",
    "font-semibold",
    "font-medium",
    "font-mono",
    "leading-relaxed",
    "tracking-widest",
    "whitespace-pre-wrap",
    "rounded-br-lg",
    "rounded-bl-lg",
    "capitalize",
    "uppercase",
    "transition",
    "transition-all",
    "transition-colors",
    "transition-shadow",
    "duration-150",
    "duration-200",
    "ease-out",
    "hover:bg-primary/80",
    "hover:bg-base-300",
    "hover:bg-base-200",
    "hover:scale-105",
    "hover:shadow-xl",
    "hover:shadow-lg",
    "focus:outline-none",
    "focus:ring-2",
    "focus:ring-primary",
    "focus:ring-indigo-500",
    "disabled:opacity-50",
    "disabled:cursor-not-allowed",
    "animate-spin",
    "animate-pulse",
    "overflow-hidden",
    "overflow-y-auto",
    "resize-none",
    "bg-gradient-to-br",
    "from-base-300",
    "via-base-200",
    "to-base-300",
  ],
  theme: {
    extend: {
      colors: {
        // Allow daisyUI to be themed with the same brand colour as the
        // custom CSS — see :root[data-theme] in src/styles/global.css.
        brand: {
          DEFAULT: "#c74634",
        },
      },
    },
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      {
        light: {
          "primary": "#c74634",
          "primary-content": "#ffffff",
          "secondary": "#2d6a4f",
          "accent": "#c74634",
          "neutral": "#1f2a37",
          "base-100": "#ffffff",
          "base-200": "#f6ede0",
          "base-300": "#f7f3ea",
          "base-content": "#1f2a37",
          "info": "#3abff8",
          "success": "#36d399",
          "warning": "#fbbd23",
          "error": "#a61b00",
        },
      },
      {
        dark: {
          "primary": "#f07159",
          "primary-content": "#0a0e14",
          "secondary": "#3d9970",
          "accent": "#f07159",
          "neutral": "#e8edf4",
          "base-100": "#1a2332",
          "base-200": "#243044",
          "base-300": "#0f1419",
          "base-content": "#e8edf4",
          "info": "#3abff8",
          "success": "#36d399",
          "warning": "#fbbd23",
          "error": "#fca5a5",
        },
      },
    ],
    base: false, // keep our custom base styles; daisyUI only contributes components
    styled: true,
    utils: true,
  },
};