export const appConfig = {
  appName: import.meta.env.VITE_APP_NAME || "Security Monitor",
  apiBaseUrl: import.meta.env.VITE_API_BASE_URL || "/api/v1",
  routes: {
    login: "/login",
    register: "/register",
    dashboard: "/dashboard",
    websites: "/websites",
    scans: "/scans",
    scanDetails: "/scans/:scanId",
    findings: "/findings",
    alerts: "/alerts",
    billing: "/billing",
    settings: "/settings",
    onboarding: "/onboarding",
    publicReport: "/public/report/:shareToken",
    security: "/security",
    status: "/status",
  },
};
