import jsPDF from "jspdf";
import "jspdf-autotable";

export function exportReportPdf({ insights, topIssues, alerts, tenantName }) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  let yPosition = margin;

  // Title
  doc.setFontSize(24);
  doc.setTextColor(199, 70, 52);
  doc.text("Security Report", margin, yPosition);
  yPosition += 15;

  // Subtitle
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated by ${tenantName || "Security Monitor"}`, margin, yPosition);
  doc.text(new Date().toLocaleDateString(), pageWidth - margin, yPosition, { align: "right" });
  yPosition += 20;

  // Summary Section
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text("Executive Summary", margin, yPosition);
  yPosition += 10;

  const avgScore = insights.length
    ? Math.round(insights.reduce((total, item) => total + item.score, 0) / insights.length)
    : 100;
  const totalIssues = topIssues.length;
  const criticalIssues = topIssues.filter((i) => i.severity === "critical").length;

  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  doc.text(`Average Security Score: ${avgScore}/100`, margin, yPosition);
  yPosition += 7;
  doc.text(`Total Issues Found: ${totalIssues}`, margin, yPosition);
  yPosition += 7;
  doc.text(`Critical Issues: ${criticalIssues}`, margin, yPosition);
  yPosition += 7;
  doc.text(`Websites Monitored: ${insights.length}`, margin, yPosition);
  yPosition += 20;

  // Website Scores Table
  if (insights.length > 0) {
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text("Website Security Scores", margin, yPosition);
    yPosition += 10;

    const tableData = insights.map((insight) => [
      insight.website.domain,
      `${insight.score}/100`,
      insight.healthLabel,
      insight.lastScanStatus,
    ]);

    doc.autoTable({
      startY: yPosition,
      head: [["Domain", "Score", "Status", "Last Scan"]],
      body: tableData,
      theme: "grid",
      headStyles: { fillColor: [199, 70, 52] },
      styles: { fontSize: 10 },
      columnStyles: {
        0: { cellWidth: 80 },
        1: { cellWidth: 30 },
        2: { cellWidth: 40 },
        3: { cellWidth: 40 },
      },
    });

    yPosition = doc.lastAutoTable.finalY + 15;
  }

  // Top Issues Section
  if (topIssues.length > 0) {
    // Check if we need a new page
    if (yPosition > pageHeight - 60) {
      doc.addPage();
      yPosition = margin;
    }

    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text("Top Security Issues", margin, yPosition);
    yPosition += 10;

    const issuesData = topIssues.map((issue) => [
      issue.humanTitle,
      issue.severity.toUpperCase(),
      issue.humanSummary?.substring(0, 80) + (issue.humanSummary?.length > 80 ? "..." : ""),
    ]);

    doc.autoTable({
      startY: yPosition,
      head: [["Issue", "Severity", "Description"]],
      body: issuesData,
      theme: "grid",
      headStyles: { fillColor: [199, 70, 52] },
      styles: { fontSize: 9 },
      columnStyles: {
        0: { cellWidth: 70 },
        1: { cellWidth: 25 },
        2: { cellWidth: 95 },
      },
    });

    yPosition = doc.lastAutoTable.finalY + 15;
  }

  // Alerts Section
  if (alerts.length > 0) {
    if (yPosition > pageHeight - 60) {
      doc.addPage();
      yPosition = margin;
    }

    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text("Recent Alerts", margin, yPosition);
    yPosition += 10;

    const alertsData = alerts.map((alert) => [
      alert.websiteDomain,
      alert.findingTitle,
      alert.channel,
      alert.status,
      alert.relativeTime,
    ]);

    doc.autoTable({
      startY: yPosition,
      head: [["Website", "Finding", "Channel", "Status", "Time"]],
      body: alertsData,
      theme: "grid",
      headStyles: { fillColor: [199, 70, 52] },
      styles: { fontSize: 9 },
      columnStyles: {
        0: { cellWidth: 50 },
        1: { cellWidth: 50 },
        2: { cellWidth: 25 },
        3: { cellWidth: 25 },
        4: { cellWidth: 40 },
      },
    });
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${pageCount} | Security Monitor Report`,
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );
  }

  // Save the PDF
  doc.save(`security-report-${new Date().toISOString().split("T")[0]}.pdf`);
}
